raimon49/pip-licenses

CHANGELOG.md, README.md, piplicenses.py, test_piplicenses.py
=> Implement 'find_license_from_classifier'

CHANGELOG.md, README.md, piplicenses.py, test_piplicenses.py
=> Implement ignore option

CHANGELOG.md, MANIFEST.in, README.md, piplicenses.py, test_piplicenses.py
=> Implement output markdown

CHANGELOG.md, README.md, piplicenses.py, test_piplicenses.py
=> Support display multiple license

CHANGELOG.md, README.md, dev-requirements.txt, piplicenses.py, test_piplicenses.py
=> Implement output Confluence and JIRA Wiki markup

CHANGELOG.md, piplicenses.py
=> Supports both pip 9.x and pip 10.x

CHANGELOG.md, README.md, piplicenses.py
=> Release new version as implement '--summary' option

CHANGELOG.md, README.md, dev-requirements.txt, piplicenses.py
=> Release new version as implement '--with-description' option

.gitignore, CHANGELOG.md, Dockerfile, README.md, dev-requirements.txt, piplicenses.py, test_piplicenses.py
=> Release 1.12.0

CHANGELOG.md, README.md, dev-requirements.txt, piplicenses.py, test_piplicenses.py
=> Release 1.14.0

CHANGELOG.md, dev-requirements.txt, piplicenses.py
=> Release 1.15.1

CHANGELOG.md, dev-requirements.txt, piplicenses.py
=> Release 1.15.2

CHANGELOG.md, dev-requirements.txt, piplicenses.py
=> Release 1.16.0 

CHANGELOG.md, README.md, piplicenses.py, test_piplicenses.py
=> Release 1.17.0

piplicenses.py
[Counter](https://docs.python.org/3/library/collections.html#collections.Counter) implements the exact pattern used here.
=> Use collections.Counter for counting

CHANGELOG.md, piplicenses.py, setup.cfg
=> Release 2.0.1

CHANGELOG.md, README.md, dev-requirements.txt, piplicenses.py
=> Release 2.1.0

CHANGELOG.md, dev-requirements.txt, piplicenses.py, setup.py
=> Release 2.1.1

CHANGELOG.md, README.md, piplicenses.py, test_piplicenses.py
This release adapts to issues #66 and #67
=> Release 2.2.0

CHANGELOG.md, dev-requirements.txt, piplicenses.py
This release adapts to issues #69
=> Release 2.2.1

test_piplicenses.py
ReST, markdown, and confluence tables are
tested with the actual installed packages.
Furthermore, the ReST table is being parsed
by docutils for errors.
=> fix: populate tables and test ReST table

CHANGELOG.md, Makefile, dev-requirements.in, dev-requirements.txt, piplicenses.py
This release will close #87 after shipping.
=> Release 3.3.0

CHANGELOG.md, dev-requirements.txt, piplicenses.py
This release is intended to fix #93
=> Release 3.3.1

piplicenses/__main__.py
Copy of #94 for the `dev-4.0.0` branch.
=> Fix license summary (dev)

README.md, piplicenses.py, test_piplicenses.py
Following the work done here https://github.com/raimon49/pip-licenses/pull/19, I tried to solve the https://github.com/raimon49/pip-licenses/issues/18, following a similar approach
=> Add --pacakges options

CHANGELOG.md, dev-requirements.txt, piplicenses.py
=> Release 3.5.1

.github/workflows/python-package.yml, CHANGELOG.md, dev-requirements.txt, piplicenses.py, setup.cfg
This release branch is fix #126
=> Release 3.5.5

.github/workflows/python-package.yml, piplicenses.py, setup.cfg, test_piplicenses.py
Especially, rather than functions that are internal to pip.
Solves https://github.com/raimon49/pip-licenses/issues/128.
=> feat: depend on importlib_metadata rather than pip

CHANGELOG.md, dev-requirements.in, dev-requirements.txt, piplicenses.py
Add type annotations and code formatter.
=> Release 4.0.2

CHANGELOG.md, piplicenses.py
This release is an improvement to `--format=html`
=> Bump version to 4.0.3

CHANGELOG.md, piplicenses.py
This release branch is fix #145
=> Release 4.1.0

README.md, piplicenses.py
=> Allow version spec in `--ignore-packages`

CHANGELOG.md, README.md, piplicenses.py, test_piplicenses.py
Version 4.2.0 received many contributions. It will be officially released after a release candidate version.
Issues to be resolved by this release:
* Fix #144 
* #151 
* #153 
* #150 
* #155
Still in the process of implementation or under discussion:
* Nothing
=> Release 4.2.0

dev-requirements.in, dev-requirements.txt
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259
=> Remove codecov package as a yanked from PyPI

CHANGELOG.md, piplicenses.py
This version includes the following PRs:
* #158
=> Bump version to 4.3.0

CHANGELOG.md, piplicenses.py, test_piplicenses.py
=> Fix normalize pkg name

CHANGELOG.md, piplicenses.py
=> Release 4.3.2

CHANGELOG.md, piplicenses.py
=> Release 4.4.0
