raimon49/pip-licenses

CHANGELOG.md
README.md
piplicenses.py
test_piplicenses.py

Implement output reST

---

CHANGELOG.md
README.md
piplicenses.py
test_piplicenses.py

Implement output HTML

---

piplicenses.py
test_piplicenses.py

This allows the user to pass `pip-licenses --summary` which then provides output like so:
```bash
$ python ./piplicenses.py --summary
Count  License
1      ASL
2      Apache 2.0
8      BSD
2      BSD License
1      BSD or Apache License, Version 2.0
1      BSD-like
2      Expat license
1      GPL
2      LGPL
14     MIT
1      MIT License
3      MIT license
1      MPL-2.0
1      PSF
2      UNKNOWN
1      http://opensource.org/licenses/MIT
1      public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)
```
All output `--format-*` flags work with `--summary`, as do `--from-classifier`, `--with-system`, `--order` and `-i`. However, due to the nature of the summary only, `--with-authors` and `--with-urls` cannot take affect when `--summary` has been activated.

Adds a summary argument

---

README.md
piplicenses.py
test_piplicenses.py

This option was very helpful to me. Hope this helps someone else.

Add --with-summary option

---

test_piplicenses.py

`assertEquals()` and `assertNotEquals()` are deprecated in favor of their singular cousins `assertEqual()` and `assertNotEqual()`.
More importantly, remove a test function that is overwriting the one before it (because they have the same name) and yet contains duplicate functionality of the one after it.

Minor test cleanup

---

README.md
piplicenses.py
setup.cfg
test_piplicenses.py

My organization needs the ability to pull the license file path and contents, similar to how npm [license-checker](https://www.npmjs.com/package/license-checker) does when using `--customPath licenseText`. This adds that functionality with the `--with-license-file` argument.
While validating this, I discovered that PTable determines vertical table layout based on the data in the row even if those fields won't be output. Hence commit 90470ab to only add fields to the row if we want to output them. I've broken that into a separate logical commit but can break it out into another PR if that would be preferred.
During testing I also found a missing development dependency, hence the updates to `dev-requirements.in` (and the re-computed `dev-requirements.txt`) in a separate commit.

Add option to pull license file path and contents

---

CHANGELOG.md
piplicenses.py

Release new version as implement '--with-license-file' option

---

Dockerfile
README.md

@raimon49 thanks for this AWESOME project!
I use it in CI for a few projects where I want to be really careful about unwanted licenses like GPL sneaking into my dependency tree.
Because I use `pip-licenses` so much, I wanted to come into the project today and spend some time learning how the internals work.
I really like the Docker setup you have, and hope you'll consider this PR that makes two small changes to it.
* Docker supports the use of `ARG` for storing (basically) environment variables that are only used at build time. I recommend centralizing the path `/opt/piplicenses` (which is manually copied in multiple places) in an `ARG` to improve the readability of your `Dockerfile` and reduce the risk of copy-paste errors if contributors add to it in the future
* While running through …

Minor fixes to Docker stuff

---

.travis.yml
CHANGELOG.md
CONTRIBUTING.md
Dockerfile
README.md
dev-requirements.txt
piplicenses.py
setup.py
test_piplicenses.py

Release 1.13.0

---

piplicenses.py

--ignore-packages short-circuits parsing the license file. This is useful for getting around really broken packages.

--ignore-packages short-circuit

---

README.md
piplicenses.py
test_piplicenses.py

Hi 👋 
I took the liberty of adding a --json-license-finder option to pip-licenses. This makes pip-licenses a drop-in replacement for LicenseFinder (https://github.com/pivotal/LicenseFinder) which is used by LicenseManagement in Gitlab's AutoDevops.
The issue with LicenseFinder is that it can only scan dependencies up until python 3.5 and not 3.6. pip-licenses is way better in that regard! However if we want to use the bindings inside Gitlab CI we need the output of pip-licenses to be the same as LicenseFinder.
From reading the source it wasn't immediately clear if pip-licenses supports overriding the json format that is outputted, if it does please point me in the right direction!
To me this seems like a clean solution. Suggestions on how to improve this PR are very welcome, this is my …

feat: Add JSONLicenseFinder

---

piplicenses.py
test_piplicenses.py

PTable and prettytable conflict, both using package name 'prettytable'
with one as prettytable.py and the other as prettytable/.
pip provides no protection against two packages conflicting like
these.
PTable hasnt maintained backwards compatability, and hasnt been
doing releases for a while.
This patch allows either to be present.

Allow using prettytable

---

CHANGELOG.md
README.md
piplicenses.py

This release is related to #51 and #52

Bump version to 1.18.0

---

piplicenses.py
test_piplicenses.py

Fixes #55.
By using `open()` rather than `codecs.open()` the newline-fixing behaviour from Python 3 can be used.
Presumably `codecs.open()` was used previously to allow proper UTF-8 handling in Python 2, but since that has been dropped the normal `open()` can be used.
Also drop some inner imports in tests and empty `setUp()` and `tearDown()` methods.
Tested with:
```
$ pip install django-cors-headers==3.2.0
$ python piplicenses.py --with-license-file --no-license-path | grep -C 2 django-cors-headers
END OF TERMS AND CONDITIONS
django-cors-headers  3.2.0       MIT License                                                   Copyright 2017 Otto Yiu and other contributors
http://ottoyiu.com
```
This showed the same breakage as in the issue before the fix.

Fix reading license files with windows newlines

---

README.md
piplicenses.py
test_piplicenses.py

Closes #49 
This matches the license style of Angular CLI (which calls [`license-webpack-plugin`](https://github.com/xz64/license-webpack-plugin) internally) and is more pleasing to view on horizontally-constrained environments (like some web pages) when license files are included.

Add --format=plain-vertical

---

README.md
piplicenses.py
test_piplicenses.py

Some package data contains Unicode characters which
might cause problems for certain output formats (in
particular ReST tables). This commit adds filtering
functionality by introducing two new options.

feat: add filtering of input data

---

README.md
piplicenses.py
test_piplicenses.py

At the moment `pip-licenses` can only output **either** the metadata **or** the classifier license information.
This PR adds the `--from=all` option that displays both license information at the same time .
**Background**
[PEP 639](https://www.python.org/dev/peps/pep-0639/) specified how Python packages are supposed to define license information going forward. The preferred way is to use the `license` metadata field with SPDX license expression [syntax](https://www.python.org/dev/peps/pep-0639/#license-expression-syntax). Although not officially deprecated, the trove classifiers will slowly be phased out and won't receive any more updates.
Since the PEP is only from Aug-2019, most packages still use the trove class and/or have outdated/invalid metadata license information. With the …

Added '--from=all' option

---

.gitignore
README.md
piplicenses.py
setup.cfg
test_piplicenses.py

Some improvements to the argument parser. This PR greatly improves the readability of the help command and introduces `Enums` for arguments.
**Current help text**
**Changes**
- `\n` in help strings are now rendered correctly
- Added argument groups and rearranged argument positions
- Updated readme to match changes
- Updated `max_help_position` to avoid unnecessary line breaks
- Added choices as additional help for `from`, `order` and `format`
- Added enums for `from`, `order` and `format`
--
I've split these changes into multiple commits to make reviewing them a bit easier.
On a related note, what is your opinion to `squash merge` for PRs? Although it might seem counterintuitive at first, I think it makes the git log much easier to read and the Github integration is better. The squash …

Improve argparser

---

piplicenses.py

In #86 I changed the way licenses are handled to allow the `--from=all` option. That meant however that the license classifier wasn't written into the package metadata anymore if the wasn't any.
This PR uses `select_license_by_source` to correctly identify which license should be counted.
Closes #93 
--
Regarding the `dev` branch: This should definitely be address there as well. However since the structure changed, a rebase on its own won't do it. I would suggest that I open and additional PR just for it once the `dev` branch is rebased correctly.

Fix license summary

---

.gitignore
README.md
piplicenses.py
test_piplicenses.py

* Changed behavior of `allow-only` and `fail-on` flags. Now you do not
need to specify exact combinations of multiple licenses.
* Updated Readme and tests

Verify multiple licenses individually

---

piplicenses.py

Without this patch [starlette-exporter](https://github.com/stephenhillier/starlette_exporter) shows a messed up `UNKNOWN` license:
```
| Name               | Version   | License                              |
|--------------------|-----------|--------------------------------------|
| starlette-exporter | 0.14.0    | K; N; O; U; W                        |
```
Patched:
```
| Name               | Version   | License                              |
|--------------------|-----------|--------------------------------------|
| starlette-exporter | 0.14.0    | Apache License 2.0                   |
```

Fix license classifier check

---

piplicenses.py
test_piplicenses.py

Alternative solution to https://github.com/raimon49/pip-licenses/pull/132. This solution ensures that parameter `license_classifier` to `select_license_by_source` is a `list`, resulting in code that is easier to reason about.

refactor: parameter license_classifier expects a list

---

.github/workflows/python-package.yml
CHANGELOG.md
piplicenses.py

Use raw distributions from importlib_metadata

---

piplicenses.py
test_piplicenses.py

This should fix broken author names etc. when viewing the output in browser.
My current workflow is to save the `--format html` output from pip-licenses straight to a file. To have non-broken author names when viewing that in a browser, need to either wrap the output in a full html document that sets an encoding or, as I'm doing now, pipe through `python -c "import sys; s = sys.stdin.read(); print(s.encode('ascii', errors='xmlcharrefreplace').decode('ascii'))"` which is basically the change in this PR.
It feels better to add this here, rather than upstream in prettytable, since that package works fine outputting utf-8 in the context of including tables in larger documents.

Escape unicode output (to e.g. &#123;) in the html output

---

README.md
piplicenses.py
test_piplicenses.py

* Matching license names with `allow-only` and `fail-on` options is no longer case-sensitive #145 
* Updated Readme and tests

Case-insensitive license name matching

---

piplicenses.py

I noticed that some packages (e.g. [termcolor](https://github.com/termcolor/termcolor)) do not declare an author (metadata field `author`) but the email address of the author (metadata field `author-email`). For this reason I think it is appropriate to use this value as a fallback value.
Current output:
```
Name       Version  License      Author                                      
termcolor  2.2.0    MIT License  UNKNOWN
```
New output:
```
Name       Version  License      Author                                      
termcolor  2.2.0    MIT License  Konstantin Lepa <konstantin.lepa@gmail.com>
```
Other examples for packages with defined `author-email` but no `author`
* https://pypi.org/project/tomli/
* https://pypi.org/project/tabulate/
* https://pypi.org/project/uvicorn/

feat: Use `author-email` metadata as fallback if `author` is None

---

README.md
piplicenses.py
test_piplicenses.py

Fixes #149
Still Work in Progress, happy to receive feedback !
Not particularly happy with the fact that you have to specify until the `site-packages` folder and not just the venv folder. suggestions welcome.

Add `--python` option

---

CHANGELOG.md
piplicenses.py
test_piplicenses.py

Hello again!
This PR basically cleans up my last fallback solution with a slightly more cleaner way to get the values from the metadata by using (type annotated) lambda functions and uses the **first** `Project-URL` value of the metadata.
Current output:
```
Name       Version  License      Author                                       URL     
termcolor  2.2.0    MIT License  Konstantin Lepa <konstantin.lepa@gmail.com>  UNKNOWN
```
New output:
```
Name            Version  License      Author                                      URL  
termcolor       2.2.0    MIT License  Konstantin Lepa <konstantin.lepa@gmail.com> https://github.com/termcolor/termcolor
```

feat: Use `Project-URL` metadata as fallback if `home-page` is None

---

README.md
piplicenses.py
test_piplicenses.py

to avoid exporting the version number of packages.
I.E. for security reasons you want to export licenses without the specific version number.

feat: adding `--no-version` option

---

piplicenses.py
test_piplicenses.py

This PR has 2 parts:
1. Switch to case-insensitive matching of fallback amongst the entries `Project-URL`. Came across many projects that do use lowercase for their entries, and previously they were listed with URL being `UNKOWN`.
2. Add `repository` as another fallback. This I see popping up quite a bit among projects, instead of `source`.
Happy to hear feedback on either of these. 1. is a blocker for us on some projects, 2. is a potential nice-to-have but optional (added in a separate commit).

package URL extraction improvements 

---

README.md

Using `cmd` via VSCode on Windows 11, I was unable to get past the `UnicodeEncodeError` either unsetting or setting these environment variables. Setting `PYTHONIOENCODING="utf-8"` did let me get things working.
Thank you for this package and your work maintaining it.

Add PYTHONIOENCODING hint to readme

---

CHANGELOG.md
piplicenses.py

This release contains #172 fixes
* Always terminate `--allow-only` and `--fail-on` messages with a newline
* Always terminate files created with `--output-file` with a newline

Release 4.3.3

---

README.md
piplicenses.py
test_piplicenses.py

This changeset introduces a way to do partial matching on license names.
Say, to match all BSD licenses for a given --fail-on=BSD.
To do so, it:
* Introduces a new cli boolean parameter (default false), called --partial-match When enabled, enables partial matching.
* Introduces code to mimic slower, partial-match inntersection/diff methods
* Introduces tests to test how this works
Fixes #187

Enable partial matching on allow-only/fail-on

---

.github/workflows/python-package.yml
dev-requirements.txt

I'm trying to use v4 because of an error uploading coverage.
OK, PRs made by dependabot was cherry picked.
Close #190 
Close #191

Update version of Codecov GitHub Action to v4

---

.github/workflows/python-package.yml
dev-requirements.txt

Update setting of GitHub Actions

---

README.md
dev-requirements.in
dev-requirements.txt
piplicenses.py
requirements.in
requirements.txt
setup.cfg
test_piplicenses.py

This PR adds possibility to set `pip-licences` input parameters from `pyproject.toml` file. The change made to be minimally invasive to project logic:
- All parameters configurable using CLI are configurable using `pyproject.toml` in the special section for `pip-licences` tool
- Inputs set in CLI have higher priority than `pyproject.toml` and can override them
- All different types of parameters parsing from toml and overriding by cli was tested in a separate test
Main motivation: https://github.com/raimon49/pip-licenses/issues/148 and I really love that in modern python packages you could configure all tools in `pyproject.toml`

Support parsing input parametres from `pyproject.toml` config

---

CHANGELOG.md
CONTRIBUTING.md
README.md
dev-requirements.txt
piplicenses.py

This release includes the following issues:
- Fix #148
- Fix #198
- Fix #199

Release 4.5.0

---

CHANGELOG.md
piplicenses.py

I missed the fact that v4.5.0 had more dependencies packages inside the system.

Release 4.5.1

---

.github/workflows/python-package.yml
CHANGELOG.md
piplicenses.py
pyproject.toml

This release contains #203 
In addition, Python 3.8 will soon be EOL.
https://devguide.python.org/versions/
Therefore, we would also like to set the lower limit of Python versions supported by pip-licenses to 3.9.

Release with pyproject.toml
